"""Editorial source for the English and Spanish screen-reset kits."""

EN_META = {
    "language": "English",
    "title": "The 7-Day School-Night Screen Reset",
    "subtitle": "A practical family kit for clearer device boundaries, more predictable transitions, and a plan you can actually repeat",
    "short_title": "School-Night Screen Reset",
    "tonight": "TONIGHT",
    "footer": "A reset is a return to the plan, not a punishment.",
    "disclaimer": "Educational planning tool. Not medical or mental-health advice.",
}

EN_PAGES = [
    {
        "type": "cover",
        "eyebrow": "A PRINTABLE ACTION KIT FOR FAMILIES WITH CHILDREN AGES 6-12",
        "title": EN_META["title"],
        "subtitle": EN_META["subtitle"],
        "badge": "START IN 10 MINUTES",
    },
    {
        "type": "quickstart",
        "kicker": "OPEN HERE FIRST",
        "title": "Your ten-minute start",
        "intro": "The hardest part is rarely deciding that screens need a boundary. It is holding that boundary at 7:42 p.m., when everyone is tired. Do not rebuild the whole household tonight. Make one decision.",
        "steps": [
            ("1", "Pick one moment", "Choose the point that causes the most friction: homework, dinner, the final game, or bedtime."),
            ("2", "Write one visible rule", "Use a sentence a child could repeat. Example: Recreational screens park at 7:30 on school nights."),
            ("3", "Give a five-minute warning", "Say what will happen next, not what the child did wrong."),
            ("4", "Offer two off-screen choices", "Keep both choices acceptable to you. A choice is not a negotiation about the boundary."),
        ],
        "script": "Five minutes left. When the timer ends, the device parks here. Then you can choose a snack with me or Lego at the table.",
        "action": "Write tonight's single boundary on a sticky note and place it where the device will park.",
    },
    {
        "type": "content",
        "kicker": "HOW TO USE THIS KIT",
        "title": "One boundary. Seven nights. Real information.",
        "intro": "This kit is a short experiment, not a verdict on your parenting. You will choose one school-night boundary, test it for seven nights, and adjust the setup instead of changing the rule in the middle of a hard moment.",
        "bullets": [
            "Use the daily pages in order. Each night adds one small skill.",
            "Separate recreational use from homework, communication, accessibility, and creative work.",
            "Keep the boundary stable. Adjust the warning, location, replacement, or timing when needed.",
            "If two caregivers disagree, settle the adult plan before asking a child to follow it.",
            "A difficult night is data. Repair, reset, and continue without adding a bigger punishment.",
        ],
        "note_title": "What this kit does not do",
        "note": "It does not diagnose screen addiction, prescribe a universal number of daily hours, or promise changes in sleep, grades, mood, or behavior. Those outcomes depend on more than a printable plan.",
        "action": "Circle the one outcome you control: a clear rule, a predictable warning, a consistent location, or a calmer response.",
    },
    {
        "type": "worksheet",
        "kicker": "BASELINE",
        "title": "Notice before you change",
        "intro": "Think about the last three school nights. Estimate honestly. Precision is less useful than a pattern you can see.",
        "prompts": [
            "Recreational screen use usually begins at:",
            "The hardest device to stop is:",
            "The hardest moment is usually:",
            "The first warning usually happens at:",
            "What happens immediately after the device turns off?",
            "What do adults usually say or do next?",
        ],
        "check_title": "What is the friction mostly about?",
        "checks": ["The ending feels sudden", "The next activity is unclear", "The rule changes by day", "Adults disagree", "The child is hungry or tired", "The content has no natural stopping point"],
        "action": "Choose the friction you can change without demanding that your child feel differently.",
    },
    {
        "type": "timeline",
        "kicker": "MAP THE NIGHT",
        "title": "Find the transition, not the villain",
        "intro": "Conflict often sits between two activities. Map the hour around your hardest moment. Include what the adults are doing, too.",
        "times": ["60 min before", "30 min before", "10 min before", "Screen ends", "10 min after"],
        "prompts": ["What is happening?", "What does the child expect?", "What does the adult expect?"],
        "note_title": "Look for a missing bridge",
        "note": "A bridge can be a timer, a saved stopping point, a snack, a shower already prepared, music, a short connection ritual, or a task broken into a first tiny step.",
        "action": "Add one bridge before the screen ends. Do not wait until the device is already in someone's hand.",
    },
    {
        "type": "worksheet",
        "kicker": "THE BOUNDARY",
        "title": "Write a rule a child can repeat",
        "intro": "A usable rule answers four questions: which screens, on which nights, when they stop, and where they go.",
        "formula": "On [nights], [recreational screens] stop at [time or event] and park at [location].",
        "prompts": [
            "Which nights does the rule cover?",
            "Which uses are included? Which necessary uses are excluded?",
            "What is the exact endpoint: clock time, episode, round, or event?",
            "Where will devices charge or park?",
            "Who follows the rule, including adults?",
        ],
        "examples": [
            "On Sunday through Thursday, games and videos stop at 7:30 and devices charge in the kitchen.",
            "On school nights, the current round is the last round after the 7:15 warning. The console rests at 7:30.",
        ],
        "action": "Read the rule aloud. If it needs a second sentence to explain, simplify it.",
    },
    {
        "type": "menu",
        "kicker": "THE LANDING PLACE",
        "title": "Plan what comes after the screen",
        "intro": "Stopping is easier when the next ten minutes are already decided. Pick options that fit your real energy, space, weather, and budget.",
        "columns": [
            ("5 minutes", ["Choose tomorrow's clothes", "Water a plant", "One-song dance", "Feed or brush a pet", "Pack the school bag", "Make a tiny snack"]),
            ("15 minutes", ["Draw a comic strip", "Build one Lego challenge", "Walk around the block", "Read together", "Prep breakfast", "Card game or puzzle"]),
            ("Low-energy", ["Audiobook and blanket", "Coloring page", "Warm shower", "Stretch on the floor", "Talk while making tea", "Sort photos for an album"]),
        ],
        "prompt": "Our two default choices after screens are:",
        "action": "Choose only two defaults for this week. A giant activity list creates another decision when everyone is tired.",
    },
    {
        "type": "meeting",
        "kicker": "THE FAMILY MEETING",
        "title": "Seven minutes, no lecture",
        "intro": "Hold this conversation before recreational screen time begins. The goal is clarity, not agreement with every feeling.",
        "beats": [
            ("1 min", "Name the problem without blame", "School nights have felt rushed after screens, and our plan has not been clear."),
            ("2 min", "State the experiment", "For seven nights, we are trying one rule and seeing what helps."),
            ("2 min", "Invite useful input", "Which warning would help: ten minutes and five minutes, or one ten-minute warning?"),
            ("1 min", "Show the parking place", "When the timer ends, the device goes here."),
            ("1 min", "Choose the next activity", "After that, you can choose A or B."),
        ],
        "note_title": "Do not ask a fake question",
        "note": "If the endpoint is not negotiable, do not ask, 'Do you think 7:30 is fair?' Offer choice where choice is real: warning style, parking label, or the next activity.",
        "action": "Schedule the meeting before the next recreational session. Put the agreement page on the table.",
    },
    {
        "type": "daily",
        "day": "NIGHT 1",
        "title": "Make the ending visible",
        "focus": "Tonight is about predictability, not perfect cooperation.",
        "steps": ["Point to the written rule before screen time starts.", "Set the agreed warning and timer.", "Move toward the parking place before the timer ends.", "Use the stop script once. Avoid adding a speech."],
        "script": "The timer ended. The device parks now. You can be disappointed, and the plan stays the same.",
        "observe": ["Did the warning happen on time?", "Was the parking place ready?", "What was the first point of friction?"],
        "action": "Rate the setup, not the child: clear / partly clear / unclear.",
    },
    {
        "type": "daily",
        "day": "NIGHT 2",
        "title": "Separate feeling from boundary",
        "focus": "A child can dislike the limit and still understand it.",
        "steps": ["Name the feeling in one short sentence.", "Repeat the boundary without defending it.", "Offer the two planned next choices.", "Give space if the child needs a minute."],
        "script": "You wanted more time. Stopping is hard. The game is done for tonight. Do you want music in the shower or a snack at the table?",
        "observe": ["Did validation become a long negotiation?", "Were both replacement choices acceptable?", "What helped the transition move again?"],
        "action": "Practice the script once before you need it. Short words are harder to find when you are frustrated.",
    },
    {
        "type": "daily",
        "day": "NIGHT 3",
        "title": "Fix the bridge",
        "focus": "If the rule is clear but the transition stalls, improve what happens immediately after.",
        "steps": ["Prepare the next activity before the warning.", "Use a concrete first step: shoes on, book open, water running.", "Join for the first two minutes when possible.", "Do not make the replacement a prize that must be earned."],
        "script": "The tablet is parked. I already put the cards on the table. Pick red or black and deal us five each.",
        "observe": ["Was there an empty gap after stopping?", "Did adult connection help?", "Was the replacement too demanding for that hour?"],
        "action": "Choose the lowest-effort bridge that genuinely fits your household.",
    },
    {
        "type": "daily",
        "day": "NIGHT 4",
        "title": "Align the adults",
        "focus": "A child should not have to decode two competing plans.",
        "steps": ["Agree privately on the endpoint and exceptions.", "Choose who gives the warning and who handles the next activity.", "Use the same short sentence.", "Discuss disagreements after the child is out of earshot."],
        "script": "We adults changed the plan yesterday, and that was confusing. Tonight the rule is the one on the page.",
        "observe": ["Did one adult reverse the other?", "Was the handoff clear?", "Which adult task needs to be simpler tomorrow?"],
        "action": "Write the adult roles beside tonight's rule: warning / parking / next step.",
    },
    {
        "type": "daily",
        "day": "NIGHT 5",
        "title": "Use exceptions without erasing the rule",
        "focus": "An exception works when it has a reason, an endpoint, and a return date.",
        "steps": ["Name the reason before the usual endpoint.", "State the temporary endpoint.", "Say when the normal plan returns.", "Do not call an unplanned surrender a special occasion."],
        "script": "Tonight the school livestream ends at 8:15, so the device parks then. Tomorrow we return to 7:30.",
        "observe": ["Was the exception necessary or convenient?", "Did the child know when normal resumed?", "Did the exception create a new problem to solve?"],
        "action": "Write one legitimate exception your family may need and the sentence that contains it.",
    },
    {
        "type": "daily",
        "day": "NIGHT 6",
        "title": "Give your child one small job",
        "focus": "Tonight you will test whether one small, age-appropriate job makes the handoff easier in your home.",
        "steps": ["Keep the endpoint fixed.", "Offer one job: manage the timer, make the parking label, or choose the next activity.", "Let the child check the tracker.", "Name the helpful action instead of calling the child 'good'."],
        "script": "You noticed the timer and parked it before I reminded you. That made the handoff quicker.",
        "observe": ["Which job was truly theirs?", "Did it fit the child's age?", "What can repeat tomorrow?"],
        "action": "Choose one job the child can own without becoming responsible for enforcing the whole plan.",
    },
    {
        "type": "daily",
        "day": "NIGHT 7",
        "title": "Keep, adjust, or replace",
        "focus": "The purpose of seven nights is to make the next decision with evidence from your home.",
        "steps": ["Review the tracker together for five minutes.", "Name one thing that became clearer.", "Choose one setup change, if needed.", "Write the plan for the next two weeks."],
        "script": "The parking place worked, but the warning was too late. We are keeping the 7:30 endpoint and moving the first warning to 7:15.",
        "observe": ["Was the boundary understandable?", "Which friction repeated?", "Did the plan protect necessary screen use?", "What is the smallest useful adjustment?"],
        "action": "Change one variable at a time. If everything changes, you will not know what helped.",
    },
    {
        "type": "scripts",
        "kicker": "SCRIPT LIBRARY",
        "title": "Before screen time begins",
        "intro": "A boundary is easier to hear before the enjoyable thing starts. Use your natural voice. Keep the information; drop any wording that sounds unlike you.",
        "scripts": [
            ("Introduce the plan", "We are trying a seven-night school-week plan. Games and videos end at 7:30 and devices charge in the kitchen."),
            ("Clarify necessary use", "Homework on the laptop can continue. Games, shorts, and shows are done at 7:30."),
            ("Offer warning choice", "Do you want one ten-minute warning or a ten-minute and five-minute warning?"),
            ("Confirm the stopping point", "Finish this round. Do not start another one after the warning."),
            ("Name the next step", "After it parks, choose shower with music or snack and cards."),
        ],
        "action": "Highlight two scripts. Rewrite them in words you would actually say in your kitchen.",
    },
    {
        "type": "scripts",
        "kicker": "SCRIPT LIBRARY",
        "title": "When time is almost up",
        "intro": "Warnings work when they contain useful information. Repeating the warning every minute turns it into background noise.",
        "scripts": [
            ("Ten minutes", "Ten minutes left. Check where you can stop or save."),
            ("Five minutes", "Five minutes. This is the last round / episode section / video."),
            ("Timer rings", "Time. Save, close, and park it."),
            ("Child says, 'One more'", "I hear you. Starting another one takes us past the plan."),
            ("Online teammates are involved", "Tell them this is your last round. We will keep the agreed endpoint."),
        ],
        "action": "Match the warning to the content. A round needs a different stopping cue from a short video feed.",
    },
    {
        "type": "scripts",
        "kicker": "SCRIPT LIBRARY",
        "title": "When pushback arrives",
        "intro": "Do not try to win the feeling. Hold the limit, protect safety, and use fewer words as emotions rise.",
        "scripts": [
            ("'That's not fair'", "You do not think it is fair. The school-night plan stays at 7:30."),
            ("'Everyone else can'", "Other families have other plans. This is ours for seven nights."),
            ("Refusal to hand it over", "I will keep the device safe while you take a minute. We can talk when voices are lower."),
            ("Adult starts to lecture", "I am going to stop talking now. The rule is on the page."),
            ("After a hard handoff", "That was rough. We will repair what needs repairing and try the same clear plan tomorrow."),
        ],
        "safety": "If anyone may be hurt or property may be damaged, prioritize safety over completing the script. Step back, reduce stimulation, and seek appropriate support when needed.",
        "action": "Pick the shortest sentence that you can still say calmly.",
    },
    {
        "type": "scripts",
        "kicker": "SCRIPT LIBRARY",
        "title": "Exceptions, mistakes, and repair",
        "intro": "Consistency does not mean pretending adults never make mistakes. Clear repair protects trust better than a defensive explanation.",
        "scripts": [
            ("Adult forgot the warning", "I missed the warning. That made the ending abrupt. You get five minutes to save, then it parks."),
            ("Adult changed the rule midstream", "I changed the plan while you were using it. That was confusing. Tonight we use the original endpoint."),
            ("Necessary use runs late", "The assignment took longer. When it is submitted, the laptop parks. Recreational apps stay closed."),
            ("Special event", "Tonight is different because of the family call. It ends at 8:00. Normal time returns tomorrow."),
            ("Morning repair", "Last night got louder than I wanted. I am sorry for yelling. The boundary still matters, and tonight I will give the warning on time."),
        ],
        "action": "Repair your part without requiring the child to apologize first.",
    },
    {
        "type": "routine",
        "kicker": "AGES 6-8",
        "title": "A routine they can see",
        "intro": "Younger school-age children often need fewer steps, a visible sequence, and adult help starting the next activity.",
        "rows": [
            ("1", "Warning", "Adult points to timer and routine card."),
            ("2", "Save and close", "Child finishes the agreed stopping point."),
            ("3", "Park", "Device goes to the same charging place."),
            ("4", "Connect", "Two minutes with an adult: hug, snack, or short chat."),
            ("5", "Next", "Child chooses one of two prepared activities."),
        ],
        "prompts": ["Our picture or symbol for 'park':", "Our two next choices:", "The adult who starts the bridge:"],
        "action": "Draw one simple icon beside each step. Let the child point to what comes next.",
    },
    {
        "type": "routine",
        "kicker": "AGES 9-12",
        "title": "A routine they can take on step by step",
        "intro": "Older children can take more responsibility for saving, setting a timer, and checking the plan. Adults still own the boundary and safety decisions.",
        "rows": [
            ("1", "Plan", "Child names a realistic stopping point before starting."),
            ("2", "Warn", "Timer gives the agreed cue; adult avoids repeated reminders."),
            ("3", "Close", "Child saves progress and logs out if needed."),
            ("4", "Park", "Device charges outside the sleep space when appropriate."),
            ("5", "Reset", "Child picks the next task or activity from the plan."),
        ],
        "prompts": ["The responsibility I can hand over:", "The responsibility the adult keeps:", "How we handle online teammates:"],
        "action": "Ask, 'Which part can you manage without me reminding you?' Keep the answer small and observable.",
    },
    {
        "type": "parking",
        "kicker": "ENVIRONMENT",
        "title": "Build a device parking station",
        "intro": "A visible home for devices ends the question, 'Where does it go?' Choose a practical location, not a symbolic punishment shelf.",
        "checks": ["Near power outlets", "Outside bedrooms when appropriate", "Visible to adults", "Safe from spills", "Enough labeled spaces", "Does not block necessary calls or accessibility tools"],
        "labels": ["Adult", "Child 1", "Child 2", "Tablet", "Console controller", "Other"],
        "prompt": "Our parking station will be:",
        "note_title": "Adults count",
        "note": "If the family rule protects dinner or bedtime, decide what adult devices do during that same window. Modeling does not require identical needs; it requires an honest plan.",
        "action": "Set up the station before announcing the rule. Empty promises are harder to follow than visible systems.",
    },
    {
        "type": "agreement",
        "kicker": "FAMILY AGREEMENT",
        "title": "Our seven-night plan",
        "fields": [
            "The school nights included are",
            "Recreational screens covered by the plan are",
            "Necessary uses that remain available are",
            "Our endpoint is",
            "Our warnings are",
            "Devices park or charge at",
            "After screens, the two default choices are",
            "Adults will support the plan by",
            "If tonight is difficult, tomorrow we will",
        ],
        "signatures": ["Caregiver", "Caregiver", "Child", "Child"],
        "note": "Signing means, 'We understand the plan.' It does not require everyone to enjoy every part of it.",
        "action": "Post the agreement where the transition happens. A plan hidden in a drawer cannot carry the boundary for you.",
    },
    {
        "type": "tracker",
        "kicker": "SEVEN-NIGHT TRACKER",
        "title": "Track the setup, not obedience",
        "intro": "Use quick marks. The goal is to notice what makes the plan easier to follow, not to grade your child.",
        "columns": ["Night", "Warning on time?", "Endpoint clear?", "Bridge ready?", "What helped / what caught us"],
        "rows": 7,
        "review": ["The part to keep:", "The repeated friction:", "One setup change for next week:"],
        "action": "Complete the row after the transition, not during it.",
    },
    {
        "type": "menu",
        "kicker": "REPLACEMENT MENU",
        "title": "Low-friction choices for real school nights",
        "intro": "These are bridges, not enrichment projects. Pick what your family will actually use on a tired Tuesday.",
        "columns": [
            ("Move", ["Hallway balloon volley", "Ten wall pushes", "Walk the dog", "One-song freeze dance", "Stretch cards", "Stair count challenge"]),
            ("Make", ["Tiny comic", "Paper airplane test", "Build a snack face", "One-photo scavenger list", "Lego copy challenge", "Tomorrow's lunch note"]),
            ("Settle", ["Audiobook", "Read side by side", "Warm drink", "Puzzle tray", "Shower playlist", "Three good questions"]),
        ],
        "prompt": "Put a star beside three choices that require no shopping or preparation.",
        "action": "Prepare one object before screen time ends: cards on the table, towel out, book open, shoes by the door.",
    },
    {
        "type": "troubleshoot",
        "kicker": "TROUBLESHOOTING",
        "title": "Change the setup before you change the promise",
        "intro": "Keep the boundary stable long enough to learn. Use the first repeated problem you see.",
        "rows": [
            ("The ending feels explosive", "Warning may be late or the stopping point may be poor", "Move the first warning earlier; agree on save/round endpoint before play"),
            ("The child keeps starting new content", "The content has no natural end", "Use a clock endpoint and block autoplay/new rounds after the warning"),
            ("Homework becomes a loophole", "Necessary and recreational use are mixed", "Name the assignment and close unrelated apps before starting"),
            ("Adults give different answers", "The adult plan is unresolved", "Pause the experiment for one adult conversation, then relaunch one rule"),
            ("The next task never starts", "The bridge is too vague or demanding", "Prepare the first tiny step and join for two minutes"),
            ("The plan works only with threats", "Consequences are doing all the work", "Shorten the rule, improve predictability, and review whether the endpoint is realistic"),
        ],
        "action": "Choose one row. Test one adjustment for two nights before adding another.",
    },
    {
        "type": "repair",
        "kicker": "AFTER A HARD NIGHT",
        "title": "Repair without erasing the boundary",
        "intro": "A reset does not require pretending the night went well. It asks each person to own what belongs to them and return to a workable plan.",
        "steps": [
            ("Regulate first", "Wait until voices and bodies are steadier. Repair is not effective while the conflict is still peaking."),
            ("Name your part", "I yelled. I changed the rule. I forgot the warning. Be specific and stop there."),
            ("Restate the plan", "An apology for delivery is not an apology for having a boundary."),
            ("Fix the setup", "Move the timer, prepare the bridge, simplify the wording, or align the adults."),
            ("Try again", "The next opportunity is the next school night, not a distant fresh start."),
        ],
        "script": "Last night got louder than I wanted. I am sorry for yelling. The 7:30 plan still matters. Tonight I will give the warning earlier and have the snack ready.",
        "action": "Write the repair sentence you may need. Keeping it ready makes defensiveness less likely.",
    },
    {
        "type": "content",
        "kicker": "WHEN THE KIT IS NOT ENOUGH",
        "title": "Know when to get more support",
        "intro": "A printable plan cannot carry every family situation. Seek qualified support when screen-related conflict is persistent, severe, or connected to broader concerns.",
        "bullets": [
            "Safety is at risk, including threats, violence, self-harm, exploitation, or unsafe online contact.",
            "Screen use repeatedly displaces eating, school attendance, hygiene, sleep opportunity, movement, or in-person relationships.",
            "The child shows severe distress that does not settle after transitions or appears across several parts of daily life.",
            "A device is essential for disability access, health monitoring, communication, or learning and the plan needs professional adaptation.",
            "Caregiver conflict makes consistent implementation impossible or unsafe.",
        ],
        "note_title": "Where to begin",
        "note": "Start with your child's pediatrician or primary-care clinician, school support team, or a licensed child and family mental-health professional. For immediate danger, use local emergency services.",
        "action": "Write the name and contact information of the first support person you would call.",
    },
    {
        "type": "sources",
        "kicker": "SOURCES & SCOPE",
        "title": "Built for action, grounded in family media planning",
        "intro": "This toolkit translates broadly accepted family-media principles into a short planning workflow. It is not a substitute for individualized professional advice.",
        "sources": [
            ("American Academy of Pediatrics", "How to Make a Family Media Plan", "healthychildren.org/English/family-life/Media/Pages/How-to-Make-a-Family-Media-Use-Plan.aspx"),
            ("American Academy of Pediatrics", "A Child-Friendly Digital World: new media recommendations", "healthychildren.org/English/news/Pages/creating-a-child-friendly-digital-world-AAP-releases-new-media-recommendations.aspx"),
            ("Pew Research Center", "How Parents Manage Screen Time for Kids (2025 survey)", "pewresearch.org/internet/2025/10/08/how-parents-manage-screen-time-for-kids/"),
            ("Singapore Ministry of Digital Development and Information", "Digital Parenting Survey (2025)", "mddi.gov.sg/newsroom/mddi-study-shows-most-parents-guide-childrens-digital-use-but-would-like-more-support/"),
        ],
        "scope": "Copyright notice: for personal household use by the purchaser. You may print copies for your own family. Do not resell, redistribute, upload, or remove this notice.",
        "closing": "Your next step is small: choose one boundary, prepare one bridge, and make tonight clearer than yesterday.",
    },
]


ES_META = {
    "language": "Español",
    "title": "El reinicio de pantallas en 7 noches escolares",
    "subtitle": "Un kit familiar práctico para poner límites más claros, hacer las transiciones más previsibles y sostener un plan que de verdad se puede repetir",
    "short_title": "Reinicio de pantallas en noches escolares",
    "tonight": "ESTA NOCHE",
    "footer": "Reiniciar es volver al plan, no aplicar un castigo.",
    "disclaimer": "Herramienta educativa de planificación. No es asesoramiento médico ni psicológico.",
}

ES_PAGES = [
    {
        "type": "cover",
        "eyebrow": "KIT DE ACCIÓN IMPRIMIBLE PARA FAMILIAS CON NIÑOS DE 6 A 12 AÑOS",
        "title": ES_META["title"],
        "subtitle": ES_META["subtitle"],
        "badge": "EMPIEZA EN 10 MINUTOS",
    },
    {
        "type": "quickstart",
        "kicker": "EMPIEZA AQUÍ",
        "title": "Tus primeros diez minutos",
        "intro": "Lo difícil casi nunca es decidir que las pantallas necesitan un límite. Lo difícil es mantenerlo a las 7:42 de la noche, cuando todos están cansados. No intentes reconstruir toda la casa hoy. Toma una sola decisión.",
        "steps": [
            ("1", "Elige un momento", "Escoge el punto que genera más fricción: tarea, cena, última partida o ir a dormir."),
            ("2", "Escribe una regla visible", "Usa una frase que el niño pueda repetir. Ejemplo: Las pantallas recreativas se guardan a las 7:30 en noches escolares."),
            ("3", "Avisa cinco minutos antes", "Di qué ocurrirá después, no qué hizo mal el niño."),
            ("4", "Ofrece dos opciones sin pantalla", "Las dos deben ser aceptables para ti. Elegir no significa negociar el límite."),
        ],
        "script": "Quedan cinco minutos. Cuando termine el temporizador, el dispositivo se guarda aquí. Después puedes elegir una merienda conmigo o Lego en la mesa.",
        "action": "Escribe el único límite de esta noche en una nota y colócala donde se guardará el dispositivo.",
    },
    {
        "type": "content",
        "kicker": "CÓMO USAR ESTE KIT",
        "title": "Un límite. Siete noches. Información real.",
        "intro": "Este kit es un experimento corto, no una evaluación de tu crianza. Elegirás un límite para noches escolares, lo probarás durante siete noches y ajustarás la preparación en vez de cambiar la regla durante un momento difícil.",
        "bullets": [
            "Usa las páginas diarias en orden. Cada noche añade una habilidad pequeña.",
            "Distingue el uso recreativo de la tarea, la comunicación, la accesibilidad y la creación.",
            "Mantén estable el límite. Ajusta el aviso, el lugar, la alternativa o el horario cuando haga falta.",
            "Si dos cuidadores no están de acuerdo, resuelvan el plan adulto antes de pedírselo al niño.",
            "Una noche difícil aporta información. Repara, vuelve al plan y continúa sin añadir un castigo mayor.",
        ],
        "note_title": "Lo que este kit no hace",
        "note": "No diagnostica adicción a las pantallas, no prescribe un número universal de horas y no promete cambios en sueño, calificaciones, ánimo o conducta. Esos resultados dependen de mucho más que un plan imprimible.",
        "action": "Marca el resultado que sí controlas: una regla clara, un aviso previsible, un lugar fijo o una respuesta más serena.",
    },
    {
        "type": "worksheet",
        "kicker": "PUNTO DE PARTIDA",
        "title": "Observa antes de cambiar",
        "intro": "Piensa en las últimas tres noches escolares. Haz una estimación honesta. La precisión importa menos que ver el patrón.",
        "prompts": [
            "El uso recreativo suele comenzar a las:",
            "El dispositivo más difícil de dejar es:",
            "El momento más difícil suele ser:",
            "El primer aviso suele ocurrir a las:",
            "¿Qué ocurre justo después de apagar el dispositivo?",
            "¿Qué suelen decir o hacer los adultos?",
        ],
        "check_title": "¿Dónde está la mayor fricción?",
        "checks": ["El final llega de golpe", "La actividad siguiente no está clara", "La regla cambia según el día", "Los adultos no coinciden", "El niño tiene hambre o sueño", "El contenido no tiene un final natural"],
        "action": "Elige la fricción que puedes cambiar sin exigir que el niño sienta algo diferente.",
    },
    {
        "type": "timeline",
        "kicker": "MAPEA LA NOCHE",
        "title": "Encuentra la transición, no al culpable",
        "intro": "El conflicto suele aparecer entre dos actividades. Mapea la hora alrededor del momento difícil. Incluye también lo que hacen los adultos.",
        "times": ["60 min antes", "30 min antes", "10 min antes", "Fin de pantalla", "10 min después"],
        "prompts": ["¿Qué está pasando?", "¿Qué espera el niño?", "¿Qué espera el adulto?"],
        "note_title": "Busca un puente que falta",
        "note": "Un puente puede ser un temporizador, un punto para guardar la partida, una merienda, la ducha preparada, música, un minuto de conexión o la primera parte de una tarea ya lista.",
        "action": "Añade un puente antes de que termine la pantalla. No esperes a que el dispositivo ya esté en disputa.",
    },
    {
        "type": "worksheet",
        "kicker": "EL LÍMITE",
        "title": "Escribe una regla que el niño pueda repetir",
        "intro": "Una regla útil responde cuatro preguntas: qué pantallas, qué noches, cuándo terminan y dónde se guardan.",
        "formula": "En [noches], [pantallas recreativas] terminan a [hora o evento] y se guardan en [lugar].",
        "prompts": [
            "¿Qué noches cubre la regla?",
            "¿Qué usos incluye? ¿Qué usos necesarios quedan fuera?",
            "¿Cuál es el final exacto: hora, episodio, partida o evento?",
            "¿Dónde se cargarán o guardarán los dispositivos?",
            "¿Quién sigue la regla, incluidos los adultos?",
        ],
        "examples": [
            "De domingo a jueves, juegos y videos terminan a las 7:30 y los dispositivos cargan en la cocina.",
            "En noches escolares, la partida actual es la última después del aviso de las 7:15. La consola descansa a las 7:30.",
        ],
        "action": "Lee la regla en voz alta. Si necesitas una segunda frase para explicarla, simplifícala.",
    },
    {
        "type": "menu",
        "kicker": "EL LUGAR DE LLEGADA",
        "title": "Planea qué ocurre después",
        "intro": "Parar es más fácil cuando los siguientes diez minutos ya están decididos. Elige opciones que encajen con la energía, el espacio, el clima y el presupuesto reales de tu familia.",
        "columns": [
            ("5 minutos", ["Elegir la ropa de mañana", "Regar una planta", "Bailar una canción", "Dar de comer a la mascota", "Preparar la mochila", "Hacer una merienda pequeña"]),
            ("15 minutos", ["Dibujar una historieta", "Un reto con bloques", "Caminar una vuelta", "Leer juntos", "Preparar el desayuno", "Cartas o rompecabezas"]),
            ("Poca energía", ["Audiolibro y manta", "Colorear", "Ducha tibia", "Estirar en el suelo", "Conversar con una bebida", "Ordenar fotos"]),
        ],
        "prompt": "Nuestras dos opciones habituales después de las pantallas son:",
        "action": "Elige solo dos opciones para esta semana. Una lista enorme crea otra decisión cuando todos están cansados.",
    },
    {
        "type": "meeting",
        "kicker": "REUNIÓN FAMILIAR",
        "title": "Siete minutos, sin sermón",
        "intro": "Hablen antes de que empiece el tiempo recreativo. La meta es claridad, no conseguir que todos disfruten cada parte del plan.",
        "beats": [
            ("1 min", "Nombra el problema sin culpar", "Las noches se sienten apuradas después de las pantallas y nuestro plan no ha sido claro."),
            ("2 min", "Explica el experimento", "Durante siete noches probaremos una regla y veremos qué ayuda."),
            ("2 min", "Pide una opinión útil", "¿Te ayuda más un aviso a los diez y cinco minutos o uno solo a los diez?"),
            ("1 min", "Muestra el lugar", "Cuando termine el temporizador, el dispositivo va aquí."),
            ("1 min", "Elige el paso siguiente", "Después puedes elegir A o B."),
        ],
        "note_title": "No hagas una pregunta falsa",
        "note": "Si la hora final no se puede negociar, no preguntes: '¿Te parece justo terminar a las 7:30?' Ofrece elección donde sea real: el tipo de aviso, la etiqueta del lugar o la actividad siguiente.",
        "action": "Programa la reunión antes de la próxima sesión recreativa. Pon el acuerdo familiar sobre la mesa.",
    },
    {
        "type": "daily",
        "day": "NOCHE 1",
        "title": "Haz visible el final",
        "focus": "Esta noche se trata de previsibilidad, no de cooperación perfecta.",
        "steps": ["Señala la regla escrita antes de empezar.", "Activa el aviso y el temporizador acordados.", "Acércate al lugar de guardado antes de que termine el tiempo.", "Usa la frase final una vez. No añadas un discurso."],
        "script": "Terminó el tiempo. El dispositivo se guarda ahora. Puedes sentirte decepcionado y el plan sigue igual.",
        "observe": ["¿El aviso llegó a tiempo?", "¿El lugar estaba listo?", "¿Cuál fue el primer punto de fricción?"],
        "action": "Evalúa la preparación, no al niño: clara / medio clara / confusa.",
    },
    {
        "type": "daily",
        "day": "NOCHE 2",
        "title": "Separa la emoción del límite",
        "focus": "El niño puede rechazar el límite y aun así entenderlo.",
        "steps": ["Nombra la emoción en una frase corta.", "Repite el límite sin defenderlo.", "Ofrece las dos opciones preparadas.", "Dale un minuto de espacio si lo necesita."],
        "script": "Querías más tiempo. Parar cuesta. El juego terminó por hoy. ¿Prefieres música en la ducha o una merienda en la mesa?",
        "observe": ["¿La validación se convirtió en negociación?", "¿Las dos opciones eran aceptables?", "¿Qué hizo avanzar la transición?"],
        "action": "Practica la frase antes de necesitarla. Las palabras cortas cuestan más cuando estás frustrado.",
    },
    {
        "type": "daily",
        "day": "NOCHE 3",
        "title": "Mejora el puente",
        "focus": "Si la regla está clara pero la transición se atasca, mejora lo que ocurre justo después.",
        "steps": ["Prepara la actividad siguiente antes del aviso.", "Usa un primer paso concreto: zapatos puestos, libro abierto o agua corriendo.", "Acompaña los primeros dos minutos cuando puedas.", "No conviertas la alternativa en un premio que debe ganarse."],
        "script": "La tableta está guardada. Ya puse las cartas en la mesa. Elige rojo o negro y reparte cinco para cada uno.",
        "observe": ["¿Quedó un vacío después de parar?", "¿Ayudó la conexión con un adulto?", "¿La alternativa pedía demasiada energía?"],
        "action": "Elige el puente de menor esfuerzo que funcione de verdad en tu casa.",
    },
    {
        "type": "daily",
        "day": "NOCHE 4",
        "title": "Alinea a los adultos",
        "focus": "El niño no debería descifrar dos planes que compiten.",
        "steps": ["Acuerden en privado el final y las excepciones.", "Decidan quién avisa y quién prepara el paso siguiente.", "Usen la misma frase corta.", "Hablen de desacuerdos fuera del alcance del niño."],
        "script": "Ayer los adultos cambiamos el plan y eso fue confuso. Esta noche usamos la regla que está en la página.",
        "observe": ["¿Un adulto contradijo al otro?", "¿El relevo fue claro?", "¿Qué tarea adulta debe ser más simple mañana?"],
        "action": "Escribe las funciones de los adultos junto a la regla: aviso / guardado / paso siguiente.",
    },
    {
        "type": "daily",
        "day": "NOCHE 5",
        "title": "Haz excepciones sin borrar la regla",
        "focus": "Una excepción funciona cuando tiene una razón, un final y una fecha de regreso.",
        "steps": ["Nombra la razón antes de la hora habitual.", "Explica el final temporal.", "Di cuándo vuelve el plan normal.", "No llames ocasión especial a una rendición improvisada."],
        "script": "Hoy la transmisión de la escuela termina a las 8:15, así que el dispositivo se guarda entonces. Mañana volvemos a las 7:30.",
        "observe": ["¿La excepción era necesaria o cómoda?", "¿El niño sabía cuándo volvía la normalidad?", "¿Creó un problema nuevo?"],
        "action": "Escribe una excepción legítima que tu familia pueda necesitar y la frase que la contiene.",
    },
    {
        "type": "daily",
        "day": "NOCHE 6",
        "title": "Dale una tarea pequeña",
        "focus": "Esta noche vas a probar si una tarea pequeña y adecuada para su edad facilita el cambio en tu casa.",
        "steps": ["Mantén fijo el final.", "Ofrece una tarea: manejar el temporizador, hacer la etiqueta o elegir la actividad siguiente.", "Deja que el niño complete el registro.", "Reconoce la acción útil en vez de decir que el niño fue 'bueno'."],
        "script": "Viste el temporizador y guardaste el dispositivo antes de que te recordara. Eso hizo más rápido el cambio.",
        "observe": ["¿Qué tarea era realmente suya?", "¿Encajaba con su edad?", "¿Qué se puede repetir mañana?"],
        "action": "Elige una tarea que el niño pueda asumir sin ser responsable de hacer cumplir todo el plan.",
    },
    {
        "type": "daily",
        "day": "NOCHE 7",
        "title": "Conserva, ajusta o sustituye",
        "focus": "Las siete noches sirven para decidir con información de tu propia casa.",
        "steps": ["Revisen el registro durante cinco minutos.", "Nombren una cosa que quedó más clara.", "Elijan un solo cambio de preparación.", "Escriban el plan para las próximas dos semanas."],
        "script": "El lugar de guardado funcionó, pero el aviso llegó tarde. Conservamos el final a las 7:30 y movemos el primer aviso a las 7:15.",
        "observe": ["¿El límite se entendía?", "¿Qué fricción se repitió?", "¿El plan protegió los usos necesarios?", "¿Cuál es el ajuste más pequeño que ayuda?"],
        "action": "Cambia una variable por vez. Si cambia todo, no sabrás qué ayudó.",
    },
    {
        "type": "scripts",
        "kicker": "FRASES LISTAS",
        "title": "Antes de que empiece",
        "intro": "Un límite se escucha mejor antes de que comience la actividad. Usa tu voz natural. Conserva la información y cambia cualquier frase que no suene a ti.",
        "scripts": [
            ("Presentar el plan", "Probaremos un plan de siete noches. Juegos y videos terminan a las 7:30 y los dispositivos cargan en la cocina."),
            ("Aclarar el uso necesario", "La tarea en la computadora puede continuar. Juegos, videos cortos y series terminan a las 7:30."),
            ("Elegir el aviso", "¿Prefieres un aviso diez minutos antes o uno a los diez y otro a los cinco?"),
            ("Confirmar el final", "Termina esta partida. No empieces otra después del aviso."),
            ("Nombrar el paso siguiente", "Después de guardarlo, puedes elegir ducha con música o merienda y cartas."),
        ],
        "action": "Marca dos frases. Reescríbelas con las palabras que de verdad usarías en tu cocina.",
    },
    {
        "type": "scripts",
        "kicker": "FRASES LISTAS",
        "title": "Cuando queda poco tiempo",
        "intro": "Los avisos funcionan cuando aportan información. Repetirlos cada minuto los convierte en ruido de fondo.",
        "scripts": [
            ("Diez minutos", "Quedan diez minutos. Busca dónde puedes parar o guardar."),
            ("Cinco minutos", "Cinco minutos. Esta es la última partida / parte del episodio / video."),
            ("Suena el temporizador", "Terminó. Guarda, cierra y llévalo a su lugar."),
            ("'Uno más'", "Te escucho. Empezar otro nos lleva más allá del plan."),
            ("Compañeros en línea", "Avísales que esta es tu última partida. Mantendremos la hora acordada."),
        ],
        "action": "Adapta el aviso al contenido. Una partida necesita un punto final distinto a una lista infinita de videos.",
    },
    {
        "type": "scripts",
        "kicker": "FRASES LISTAS",
        "title": "Cuando aparece la resistencia",
        "intro": "No intentes ganar contra la emoción. Mantén el límite, protege la seguridad y usa menos palabras cuando sube la intensidad.",
        "scripts": [
            ("'No es justo'", "Piensas que no es justo. El plan de noches escolares sigue a las 7:30."),
            ("'A todos los dejan'", "Otras familias tienen otros planes. Este es el nuestro durante siete noches."),
            ("No quiere entregarlo", "Voy a mantener el dispositivo seguro mientras te tomas un minuto. Hablamos cuando bajen las voces."),
            ("El adulto empieza un sermón", "Voy a dejar de hablar ahora. La regla está en la página."),
            ("Después de un cambio difícil", "Fue una noche difícil. Repararemos lo necesario y mañana probaremos el mismo plan claro."),
        ],
        "safety": "Si alguien puede lastimarse o puede haber daños, prioriza la seguridad. Aléjate, reduce la estimulación y busca apoyo adecuado cuando sea necesario.",
        "action": "Elige la frase más corta que todavía puedas decir con calma.",
    },
    {
        "type": "scripts",
        "kicker": "FRASES LISTAS",
        "title": "Excepciones, errores y reparación",
        "intro": "Ser consistente no significa fingir que los adultos nunca se equivocan. Una reparación clara protege más la confianza que una explicación defensiva.",
        "scripts": [
            ("El adulto olvidó el aviso", "Olvidé avisarte y el final llegó de golpe. Tienes cinco minutos para guardar y después se apaga."),
            ("El adulto cambió la regla", "Cambié el plan mientras lo usabas y eso fue confuso. Hoy usamos la hora original."),
            ("La tarea se alargó", "La tarea tomó más tiempo. Cuando la entregues, la computadora se guarda. Las aplicaciones recreativas siguen cerradas."),
            ("Evento especial", "Hoy es diferente por la llamada familiar. Termina a las 8:00. Mañana vuelve el horario normal."),
            ("Reparación por la mañana", "Anoche levanté la voz y lo siento. El límite sigue siendo importante. Hoy avisaré a tiempo."),
        ],
        "action": "Repara tu parte sin exigir que el niño se disculpe primero.",
    },
    {
        "type": "routine",
        "kicker": "EDADES 6-8",
        "title": "Una rutina que puedan ver",
        "intro": "Los niños más pequeños suelen necesitar menos pasos, una secuencia visible y ayuda adulta para empezar la actividad siguiente.",
        "rows": [
            ("1", "Aviso", "El adulto señala el temporizador y la tarjeta de rutina."),
            ("2", "Guardar y cerrar", "El niño termina en el punto acordado."),
            ("3", "Estacionar", "El dispositivo va siempre al mismo lugar de carga."),
            ("4", "Conectar", "Dos minutos con un adulto: abrazo, merienda o charla corta."),
            ("5", "Seguir", "El niño elige una de dos actividades preparadas."),
        ],
        "prompts": ["Nuestro dibujo para 'guardar':", "Nuestras dos opciones siguientes:", "El adulto que inicia el puente:"],
        "action": "Dibuja un icono sencillo junto a cada paso. Deja que el niño señale qué viene después.",
    },
    {
        "type": "routine",
        "kicker": "EDADES 9-12",
        "title": "Una rutina con más autonomía",
        "intro": "Los niños mayores pueden asumir más responsabilidad al guardar, programar un temporizador y revisar el plan. Los adultos siguen a cargo del límite y la seguridad.",
        "rows": [
            ("1", "Planear", "El niño elige un punto realista para terminar antes de empezar."),
            ("2", "Avisar", "El temporizador da la señal; el adulto evita recordatorios constantes."),
            ("3", "Cerrar", "El niño guarda el progreso y cierra la sesión si hace falta."),
            ("4", "Estacionar", "El dispositivo carga fuera del lugar de dormir cuando sea apropiado."),
            ("5", "Reiniciar", "El niño elige la siguiente tarea o actividad del plan."),
        ],
        "prompts": ["La responsabilidad que puedo entregar:", "La responsabilidad que conserva el adulto:", "Cómo manejamos a los compañeros en línea:"],
        "action": "Pregunta: '¿Qué parte puedes manejar sin que te lo recuerde?' Mantén la respuesta pequeña y observable.",
    },
    {
        "type": "parking",
        "kicker": "EL ENTORNO",
        "title": "Crea un lugar para los dispositivos",
        "intro": "Un hogar visible para los dispositivos responde la pregunta: '¿Dónde va?' Elige un lugar práctico, no un estante de castigo.",
        "checks": ["Cerca de enchufes", "Fuera de dormitorios cuando corresponda", "Visible para adultos", "Seguro contra líquidos", "Con espacios etiquetados", "No bloquea llamadas necesarias ni accesibilidad"],
        "labels": ["Adulto", "Niño 1", "Niño 2", "Tableta", "Control de consola", "Otro"],
        "prompt": "Nuestro lugar para dispositivos será:",
        "note_title": "Los adultos también cuentan",
        "note": "Si la regla protege la cena o la hora de dormir, decide qué harán los dispositivos adultos en ese periodo. Dar ejemplo no exige necesidades idénticas; exige un plan honesto.",
        "action": "Prepara el lugar antes de anunciar la regla. Los sistemas visibles son más fáciles de seguir que una promesa vacía.",
    },
    {
        "type": "agreement",
        "kicker": "ACUERDO FAMILIAR",
        "title": "Nuestro plan de siete noches",
        "fields": [
            "Las noches escolares incluidas son",
            "Las pantallas recreativas incluidas son",
            "Los usos necesarios que siguen disponibles son",
            "Nuestro punto final es",
            "Nuestros avisos son",
            "Los dispositivos se guardan o cargan en",
            "Después de las pantallas, las dos opciones habituales son",
            "Los adultos apoyaremos el plan de esta manera",
            "Si hoy es difícil, mañana haremos lo siguiente",
        ],
        "signatures": ["Cuidador", "Cuidador", "Niño", "Niño"],
        "note": "Firmar significa: 'Entendemos el plan'. No exige que todos disfruten cada parte.",
        "action": "Coloca el acuerdo donde ocurre la transición. Un plan guardado en un cajón no puede ayudarte a mantener el límite.",
    },
    {
        "type": "tracker",
        "kicker": "REGISTRO DE SIETE NOCHES",
        "title": "Evalúa la preparación, no la obediencia",
        "intro": "Usa marcas rápidas. La meta es notar qué hace que el plan sea más fácil de seguir, no calificar al niño.",
        "columns": ["Noche", "¿Aviso a tiempo?", "¿Final claro?", "¿Puente listo?", "Qué ayudó / qué nos frenó"],
        "rows": 7,
        "review": ["La parte que conservamos:", "La fricción que se repitió:", "Un cambio para la próxima semana:"],
        "action": "Completa la fila después de la transición, no durante ella.",
    },
    {
        "type": "menu",
        "kicker": "MENÚ DE ALTERNATIVAS",
        "title": "Opciones sencillas para noches reales",
        "intro": "Son puentes, no proyectos educativos. Elige lo que tu familia usaría de verdad un martes cansado.",
        "columns": [
            ("Moverse", ["Voleibol con globo", "Diez empujes a la pared", "Pasear al perro", "Baile congelado", "Tarjetas de estiramiento", "Contar escaleras"]),
            ("Crear", ["Historieta pequeña", "Avión de papel", "Cara con la merienda", "Lista para buscar objetos", "Reto con bloques", "Nota para el almuerzo"]),
            ("Calmarse", ["Audiolibro", "Leer lado a lado", "Bebida tibia", "Rompecabezas", "Música en la ducha", "Tres preguntas buenas"]),
        ],
        "prompt": "Marca tres opciones que no necesiten compras ni preparación.",
        "action": "Prepara un objeto antes del final: cartas en la mesa, toalla lista, libro abierto o zapatos junto a la puerta.",
    },
    {
        "type": "troubleshoot",
        "kicker": "AJUSTES",
        "title": "Cambia la preparación antes que la promesa",
        "intro": "Mantén estable el límite el tiempo suficiente para aprender. Empieza por el primer problema que se repite.",
        "rows": [
            ("El final explota", "El aviso puede llegar tarde o el punto final es malo", "Adelanta el primer aviso y acuerda dónde guardar antes de jugar"),
            ("Empieza contenido nuevo", "El contenido no tiene un final natural", "Usa una hora fija y bloquea nuevas partidas o reproducción automática"),
            ("La tarea se vuelve una excusa", "Se mezclan usos necesarios y recreativos", "Nombra la tarea y cierra aplicaciones que no corresponden"),
            ("Los adultos responden distinto", "El plan adulto no está resuelto", "Pausa para una conversación adulta y relanza una sola regla"),
            ("La tarea siguiente no empieza", "El puente es vago o difícil", "Prepara el primer paso y acompaña durante dos minutos"),
            ("Solo funciona con amenazas", "Las consecuencias hacen todo el trabajo", "Acorta la regla, mejora la previsibilidad y revisa si la hora es realista"),
        ],
        "action": "Elige una fila. Prueba un ajuste durante dos noches antes de añadir otro.",
    },
    {
        "type": "repair",
        "kicker": "DESPUÉS DE UNA NOCHE DIFÍCIL",
        "title": "Repara sin borrar el límite",
        "intro": "Volver al plan no exige fingir que la noche salió bien. Pide que cada persona asuma su parte y regrese a algo que sí puede funcionar.",
        "steps": [
            ("Primero, regular", "Espera a que las voces y los cuerpos estén más tranquilos. No se repara en el punto máximo del conflicto."),
            ("Nombra tu parte", "Grité. Cambié la regla. Olvidé avisar. Sé específico y detente ahí."),
            ("Repite el plan", "Pedir disculpas por la forma no significa disculparse por tener un límite."),
            ("Arregla la preparación", "Mueve el temporizador, prepara el puente, simplifica la frase o alinea a los adultos."),
            ("Prueba otra vez", "La siguiente oportunidad es la próxima noche escolar, no un nuevo comienzo lejano."),
        ],
        "script": "Anoche levanté la voz y lo siento. El plan de las 7:30 sigue siendo importante. Hoy avisaré antes y tendré la merienda lista.",
        "action": "Escribe la frase de reparación que podrías necesitar. Tenerla preparada reduce la defensa.",
    },
    {
        "type": "content",
        "kicker": "CUANDO EL KIT NO ES SUFICIENTE",
        "title": "Reconoce cuándo necesitas más apoyo",
        "intro": "Un plan imprimible no puede resolver todas las situaciones familiares. Busca apoyo cualificado cuando el conflicto sea persistente, grave o esté conectado con otras preocupaciones.",
        "bullets": [
            "Existe un riesgo de seguridad: amenazas, violencia, autolesión, explotación o contacto inseguro en línea.",
            "El uso desplaza de forma repetida la alimentación, la escuela, la higiene, la oportunidad de dormir, el movimiento o las relaciones presenciales.",
            "El niño muestra un malestar intenso que no baja después de las transiciones o aparece en varias partes de la vida diaria.",
            "El dispositivo es esencial para accesibilidad, monitoreo de salud, comunicación o aprendizaje y el plan necesita adaptación profesional.",
            "El conflicto entre cuidadores vuelve imposible o insegura la aplicación del plan.",
        ],
        "note_title": "Por dónde empezar",
        "note": "Comienza con el pediatra o profesional de atención primaria, el equipo de apoyo escolar o un profesional acreditado de salud mental infantil y familiar. Si existe un peligro inmediato, usa los servicios de emergencia locales.",
        "action": "Escribe el nombre y contacto de la primera persona de apoyo a la que llamarías.",
    },
    {
        "type": "sources",
        "kicker": "FUENTES Y ALCANCE",
        "title": "Creado para actuar, basado en planificación familiar",
        "intro": "Este kit convierte principios ampliamente aceptados sobre medios familiares en un proceso breve. No sustituye el asesoramiento profesional individual.",
        "sources": [
            ("American Academy of Pediatrics", "How to Make a Family Media Plan", "healthychildren.org/English/family-life/Media/Pages/How-to-Make-a-Family-Media-Use-Plan.aspx"),
            ("American Academy of Pediatrics", "A Child-Friendly Digital World: new media recommendations", "healthychildren.org/English/news/Pages/creating-a-child-friendly-digital-world-AAP-releases-new-media-recommendations.aspx"),
            ("Pew Research Center", "How Parents Manage Screen Time for Kids (encuesta 2025)", "pewresearch.org/internet/2025/10/08/how-parents-manage-screen-time-for-kids/"),
            ("Ministerio de Desarrollo Digital e Información de Singapur", "Digital Parenting Survey (2025)", "mddi.gov.sg/newsroom/mddi-study-shows-most-parents-guide-childrens-digital-use-but-would-like-more-support/"),
        ],
        "scope": "Aviso de derechos: uso personal del hogar comprador. Puedes imprimir copias para tu familia. No se permite revender, redistribuir, subir ni eliminar este aviso.",
        "closing": "Tu siguiente paso es pequeño: elige un límite, prepara un puente y haz que esta noche sea más clara que ayer.",
    },
]
